### ISSUE TITLE
Improve Default BaseDSN field in MySQBackendConfig

### ISSUE THREAD

**Issue by shawnHartsell** [InVisionApp/go-master#15]
When setting up the setting up the defaults for the MySQLBackendConfig. If a BaseDSN is not supplied by a called then it will default to this structure:

`fmt.Sprintf("%s:%s@tcp(%s:%d)/?parseTime=true", m.User, m.Password, m.Host, m.Port)`

This DSN is missing a few critical items:

- database name: if this field is missing then a lock can't be required if the database server becomes unavailable
- timeouts: not having a timeout defined means that calls can wait forever. This is exacerbated if the issue occurs during the master heartbeat

**Comment by changsongl** [comment]
I have same issue with database name bug. 
`“failed to acquire lock while becoming master: failed to fetch current master state: Error 1046: No database selected”` 

Right now, I just use my own DSN instead of giving all mysql connection parameters. And I also fix the timeout problems by passing BaseDSN.

**Comment by maxcnunes** [comment]
This project is no longer actively supported and will be archived. Therefore all issues and pull requests are being closed. Please, feel free to fork it and apply the proposed change.
